### ISSUE TITLE
Update of value when modulating ...

### ISSUE THREAD

**Issue by eloimaduell** [PlaymodesStudio/MIRABCN_Generator#26]
Yesterday I think that when applying a modulation ... the modulated value was "moving" and updating on the Oscilator GUI ... now it doesn't ... This makes that as ex. if you modulate first "random addition" ... so your wave if full of "anomalies" ... then you change the modulation to "n-waves" ... what happens now is that my resulting wave is still full of "random addition" anomalies, but the value on the GUI says 0 ... so we arribe to a non-coherent state (GUI vs result) which we should avoid ... 

I remember to talk about it with Mr.Frigola, but not sure why it's not possible to achieve ...

**Comment by eduardfrigola** [comment]
It is implemented to do so, [here](https://github.com/PlaymodesStudio/MIRABCN_Generator/blob/master/src/elementOscilator.cpp#L84)

 Because we use the same oscillator bank to compute all the oscillators, if you don't change it without event you will have the parameter updated 12 times (in this case) every update. That won't show what is happening.

A possible solution will be to retrigger all parameters when you change the modulation type, it will be a good solution for you, Mr. Maduell?
