### ISSUE TITLE
openframeworks 0.9.2 and ofxExprtk 

### ISSUE THREAD

**Issue by ArashPartow** [PlaymodesStudio/MIRABCN_Generator#27]
In the readme.md there is a mention that ofxExprtk does not work with openframeworks 0.9.2.

I've just tried versions 0.9.0 - 0.9.5 of openframeworks using ofxExprtk in simple graph drawing application and don't see any errors or warnings.

ExprTk is self contained and does not rely on any other third-party libraries other than the C++ standard libraries and does not interfere with any third-party libraries or frameworks

---

So with that being said, if possible could you please further clarify what is the actual problem? - and if it's _related_ to ExprTk I'll endeavour to resolve the issue.

**Comment by eduardfrigola** [comment]
Hi, Arash! Thanks a lot for your library, it's amazing and very useful!
The problem I had is that I was developing in a machine with of 0.9.3 and everything worked as expected.
Then I tried to compile it in another machine with of 0.9.2 and it compiled but broke the execution inside your library, the exprtk.h file. I didn't really get mad with it and I tried to put of 0.9.3 (the newest at that moment) and everything was working fine. the last time I tried to compile  the project was before adding our ofxExprt addon, that is used as a bridge to openframeworks (or at least as a bridge to our code), also I made a template class that I haven't done it before. For all that reasons I assumed ofxExprtk was the reason for the project from not compiling under 0.9.2, but probably due to my mistakes in this, let's call it, bridge to openframeworks.

I will try to reproduce the error I received. Where did the program broke. And I will dig more into it hoping to help you. Either to say it's my fault or to give a clue of what in Exprtk.h is going wrong (I suppose the first choice is the most probable one 😖 ).

Thank you for you comprehension, and hope I can help you!

Eduard

**Comment by ArashPartow** [comment]
@Eduard: Thanks for comments. Based on what you've said, I'll close this issue, but if you do happen find a way to replicate the problem you encountered, feel free to reopen it and we'll proceed from there.

**Comment by eduardfrigola** [comment]
@ArashPartow: I had stored all the openframeworks old folder and i could restore the problem. I dig a little into it but I could not find what is causing the error. The error is inside exprtk.hpp. I made a simple video debugging the app until it breaks. I also zipped the app in the version it is crashing for your testing purposes, if you want.

[MIRABCN_Generator_crashing.zip](https://github.com/PlaymodesStudio/MIRABCN_Generator/files/548576/MIRABCN_Generator_crashing.zip)

**Comment by ArashPartow** [comment]
I had a look at your video, but can't make heads or tails of what it is you're seeing or attempting to demonstrate.

> The error is inside exprtk.hpp

Where abouts in ExprTk is this error occurring? - do you have a line number? Is there a call stack you can provide?

As an example: What is the expression being evaluated when the error occurs? is it any expression?

Why does the error not occur in verion 0.9.3 openframeworks? How does that version of the framework interfere with a library that has nothing to do with it? no common code between the two libraries.

Assuming you're using the same version of ExprTk and different versions of openframeworks both of which have nothing to do with each other, how is ExprTk causing the error?

What makes it work with 0.9.3 and not with 0.9.2? Does this all not seem a bit strange to you?

---

That being said, could you make a simple small example that demonstrates the error using only your ofxexprtk wrapper and none of your other components? 

As there's really no need for videos, a well written 20-30 line example will be infinitely more informative than a grainy video.
