### ISSUE TITLE
Manual Order dropdown from XML ?

### ISSUE THREAD

**Issue by eloimaduell** [PlaymodesStudio/MIRABCN_Generator#9]
Might be nice, to have a "Manual Order" dropdown with pre-selected orders that get read from a XML on startup, so it's easy to add many and new easily ?

(i got tired of getting back to 1-2-3...-12 every 5 min...)

**Comment by santi-playmodes** [comment]
dropdown xml en aquest cas mola, perque nomes son 12 elements.pero en el futur ens trobarem de nou amb el tema de les transformacions de index, quan tinguem centenars de index que manipular.Realment molaria trobar models matematics de generacio de successions numèriques,transformacions de cartesianes a polars, simetries bidimensionals…La idea de samplejar de un png les escales de grisos esta bé,pero em semblaria mes elgant poderho fer algoritmicament, digue’m maniatic…Res, coses per pensar quan tinguem temps lliure i mesos de recerca per menjar pandilla drakis i fer mates guapes…El 18/10/2016, a les 23:08, Eloi Maduell Garcia notifications@github.com va escriure:Might be nice, to have a "Manual Order" dropdown with pre-selected orders that get read from a XML on startup, so it's easy to add many and new easily ?(i got tired of getting back to 1-2-3...-12 every 5 min...)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PlaymodesStudio/MIRABCN_Generator","title":"PlaymodesStudio/MIRABCN_Generator","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/PlaymodesStudio/MIRABCN_Generator" class="">https://github.com/PlaymodesStudio/MIRABCN_Generator</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Manual Order dropdown from XML ? (#9)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/PlaymodesStudio/MIRABCN_Generator/issues/9" class="">https://github.com/PlaymodesStudio/MIRABCN_Generator/issues/9</a>"}}}
